const sampleTrades = [
  ["2025-01-08","NASDAQ","금리 공포, 기술주는 더 흔들릴 수 있습니다","금리 부담으로 기술주 약세 전망","DOWN",19410,19478,.82,.0031,"https://www.youtube.com/"],
  ["2025-01-15","KOSPI","외국인 수급이 돌아오는 신호","수급 개선으로 국내 증시 상승 전망","UP",2496,2484,.76,-.0022,"https://www.youtube.com/"],
  ["2025-02-04","NASDAQ","빅테크 실적, 기대를 낮춰야 합니다","실적 불확실성으로 조정 가능성","DOWN",19612,19654,.71,.0014,"https://www.youtube.com/"],
  ["2025-02-18","KOSPI","반도체가 코스피를 끌어올릴까","반도체 반등과 지수 상승 전망","UP",2612,2630,.68,.0052,"https://www.youtube.com/"],
  ["2025-03-05","NASDAQ","관세 충격은 이제 시작입니다","정책 위험으로 나스닥 하락 전망","DOWN",18240,18110,.91,-.0061,"https://www.youtube.com/"],
  ["2025-03-14","KOSPI","코스피 바닥을 확인했습니다","저점 통과 및 반등 전망","UP",2564,2578,.78,.0041,"https://www.youtube.com/"],
  ["2025-04-03","NASDAQ","증시 급락, 아직 끝나지 않았다","추가 하락 가능성 강조","DOWN",16902,17210,.87,.0152,"https://www.youtube.com/"],
  ["2025-04-09","KOSPI","지금은 현금을 지켜야 할 때","변동성 확대와 약세 전망","DOWN",2318,2294,.84,-.0084,"https://www.youtube.com/"],
  ["2025-04-24","NASDAQ","기술주 반등의 조건이 갖춰졌다","빅테크 중심 상승 전망","UP",17760,17895,.73,.0065,"https://www.youtube.com/"],
  ["2025-05-08","KOSPI","새 정부 기대감, 증시가 먼저 움직인다","정책 기대에 따른 상승 전망","UP",2576,2594,.75,.0057,"https://www.youtube.com/"],
  ["2025-05-21","NASDAQ","나스닥, 전고점 돌파가 보입니다","상승 추세 지속 전망","UP",19205,19145,.8,-.0024,"https://www.youtube.com/"],
  ["2025-06-05","KOSPI","코스피 3000 시대가 옵니다","국내 증시 강세 전망","UP",2780,2812,.92,.0096,"https://www.youtube.com/"],
  ["2025-06-18","NASDAQ","중동 리스크를 무시하면 안 됩니다","지정학 위험으로 하락 전망","DOWN",19510,19602,.69,.0038,"https://www.youtube.com/"],
  ["2025-07-03","KOSPI","급등 뒤에는 쉬어갈 시간이 필요합니다","단기 과열과 조정 전망","DOWN",3078,3052,.77,-.0069,"https://www.youtube.com/"],
  ["2025-07-17","NASDAQ","AI 랠리, 아직 절반도 안 왔다","기술주 추가 상승 전망","UP",20240,20308,.81,.0027,"https://www.youtube.com/"],
  ["2025-07-28","KOSPI","세제 개편이 증시를 누를 수 있습니다","정책 불확실성으로 약세 전망","DOWN",3190,3214,.72,.0061,"https://www.youtube.com/"],
  ["2025-08-06","NASDAQ","고용 둔화는 오히려 호재입니다","금리 인하 기대로 상승 전망","UP",20612,20518,.74,-.0038,"https://www.youtube.com/"],
  ["2025-08-19","KOSPI","외국인이 다시 한국을 봅니다","외국인 매수로 상승 전망","UP",3210,3195,.66,-.0037,"https://www.youtube.com/"],
  ["2025-09-04","NASDAQ","9월 조정에 대비해야 합니다","계절성과 밸류에이션 부담","DOWN",21120,21262,.85,.0054,"https://www.youtube.com/"],
  ["2025-09-18","KOSPI","반도체 랠리는 이제 시작입니다","반도체 주도 상승 전망","UP",3345,3370,.88,.0063,"https://www.youtube.com/"]
].map((x,i)=>({id:i+1,date:x[0],market:x[1],title:x[2],reason:x[3],prediction:x[4],open:x[5],close:x[6],confidence:x[7],benchmarkReturn:x[8],url:x[9]}));

let trades=[...sampleTrades],market="ALL",strategy="inverse",resultFilter="ALL",cost=.001,expanded=false,timelineExpanded=false,search="";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtPct=n=>`${n>=0?"+":""}${(n*100).toFixed(2)}%`;
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function enriched(){return trades.map(t=>{const actualRet=(t.close/t.open)-1;const actual=actualRet>=0?"UP":"DOWN";const outcome=actual===t.prediction?"SAME":"OPPOSITE";const predicted=t.prediction==="UP"?actualRet:-actualRet;return{...t,actualRet,actual,outcome,ret:(strategy==="inverse"?-predicted:predicted)-cost,position:strategy==="inverse"?(t.prediction==="UP"?"SHORT":"LONG"):(t.prediction==="UP"?"LONG":"SHORT")}})}
function filtered(){return enriched().filter(t=>(market==="ALL"||t.market===market)&&(resultFilter==="ALL"||t.outcome===resultFilter)&&t.title.toLowerCase().includes(search.toLowerCase()))}
function thumbnail(t){if(t.thumbnail)return escapeHtml(t.thumbnail);const id=(t.url.match(/(?:v=|youtu\.be\/)([\w-]{6,})/)||[])[1];if(id)return`https://i.ytimg.com/vi/${id}/mqdefault.jpg`;const bg=t.market==="NASDAQ"?"17231d":"293749",accent=t.prediction==="UP"?"c8ff32":"ff6b5f",label=encodeURIComponent(t.market+" · "+(t.prediction==="UP"?"상승 전망":"하락 전망"));return`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='320' height='180'%3E%3Crect width='100%25' height='100%25' fill='%23${bg}'/%3E%3Cpath d='M0 145 L80 100 150 125 230 48 320 78' fill='none' stroke='%23${accent}' stroke-width='8'/%3E%3Ctext x='18' y='35' fill='white' font-family='sans-serif' font-size='18' font-weight='700'%3E${label}%3C/text%3E%3Ccircle cx='285' cy='145' r='23' fill='white' fill-opacity='.9'/%3E%3Cpath d='M279 133l17 12-17 12z' fill='%23151713'/%3E%3C/svg%3E`}
function stats(rows){let equity=1,peak=1,mdd=0;const curve=[{date:rows[0]?.date||"—",value:1,bench:1}];let bench=1;rows.forEach(t=>{equity*=1+t.ret;bench*=1+t.benchmarkReturn;peak=Math.max(peak,equity);mdd=Math.min(mdd,equity/peak-1);curve.push({date:t.date,value:equity,bench})});const mean=rows.reduce((s,t)=>s+t.ret,0)/(rows.length||1);const variance=rows.reduce((s,t)=>s+(t.ret-mean)**2,0)/(Math.max(1,rows.length-1));return{total:equity-1,bench:bench-1,win:rows.filter(t=>t.ret>0).length/(rows.length||1),mdd,sharpe:variance?mean/Math.sqrt(variance)*Math.sqrt(rows.length):0,curve}}
function render(){const rows=filtered(),s=stats(rows);$("#totalReturn").textContent=fmtPct(s.total);$("#returnDelta").textContent=fmtPct(s.total-s.bench);$("#winRate").textContent=`${(s.win*100).toFixed(1)}%`;$("#maxDrawdown").textContent=fmtPct(s.mdd);$("#tradeCount").textContent=rows.length;$("#nasdaqCount").textContent=rows.filter(x=>x.market==="NASDAQ").length;$("#kospiCount").textContent=rows.filter(x=>x.market==="KOSPI").length;$("#sharpe").textContent=s.sharpe.toFixed(2);$("#sharpeGrade").textContent=s.sharpe>=1?"GOOD":s.sharpe>=0?"NEUTRAL":"WEAK";$("#chartReturn").textContent=fmtPct(s.total);$("#chartPeriod").textContent=rows.length?`${rows[0].date.replaceAll("-",".")} — ${rows.at(-1).date.replaceAll("-",".")}`:"데이터 없음";$("#rowCount").textContent=rows.length;
  renderStory(rows);
  $("#winBars").innerHTML=rows.map(t=>`<i class="${t.ret>0?"win":""}" style="height:${Math.max(3,Math.min(18,Math.abs(t.ret)*800))}px"></i>`).join("");
  const shown=expanded?rows:rows.slice(0,7);$("#tradesBody").innerHTML=shown.map(t=>`<tr><td class="mono">${t.date.replaceAll("-",".")}</td><td><span class="market-tag">${t.market}</span></td><td class="video-cell"><div class="table-video"><img src="${thumbnail(t)}" alt=""/><div><a href="${escapeHtml(t.url)}" target="_blank" rel="noreferrer">${escapeHtml(t.title)}</a><small>${escapeHtml(t.reason||"분류 근거 없음")}</small></div></div></td><td><span class="direction-tag ${t.prediction==="UP"?"up":"down"}">${t.prediction==="UP"?"▲ 상승":"▼ 하락"}</span></td><td><span class="direction-tag ${t.actual==="UP"?"up":"down"}">${t.actual==="UP"?"▲ 상승":"▼ 하락"}</span></td><td><span class="verdict ${t.outcome.toLowerCase()}">${t.outcome==="OPPOSITE"?"↔ 반대로 감":"✓ 예측대로"}</span></td><td class="right mono ${t.actualRet>=0?"return-pos":"return-neg"}">${fmtPct(t.actualRet)}</td></tr>`).join("")||`<tr><td colspan="7" style="text-align:center;padding:40px;color:var(--muted)">조건에 맞는 영상이 없습니다.</td></tr>`;
  $("#showMoreBtn").textContent=expanded?"접기":"전체 거래 보기";renderSignals(rows);renderChart(s.curve)}
function renderSignals(rows){$("#signalStats").innerHTML=["UP","DOWN"].map(dir=>{const a=rows.filter(x=>x.prediction===dir),rate=a.filter(x=>x.ret>0).length/(a.length||1);return`<div><div class="signal-item-head"><b class="${dir.toLowerCase()}">${dir==="UP"?"▲ 상승 예측 → 반대 매매":"▼ 하락 예측 → 반대 매매"}</b><span>${(rate*100).toFixed(0)}%</span></div><div class="progress"><i style="width:${rate*100}%"></i></div><div class="signal-meta"><span>${a.length} TRADES</span><span>${a.filter(x=>x.ret>0).length} WIN / ${a.filter(x=>x.ret<=0).length} LOSS</span></div></div>`}).join("")}
function renderStory(rows){const opposite=rows.filter(x=>x.outcome==="OPPOSITE").length,rate=opposite/(rows.length||1),same=1-rate;$("#oppositeHeadline").textContent=`${(rate*100).toFixed(0)}%`;$("#oppositePct").textContent=`${(rate*100).toFixed(0)}%`;$("#samePct").textContent=`${(same*100).toFixed(0)}%`;$("#oppositeMeter").style.width=`${rate*100}%`;$("#sameMeter").style.width=`${same*100}%`;$("#summarySentence").textContent=`확인한 영상 ${rows.length}개 중 ${opposite}개에서 전망과 실제 시장 방향이 달랐습니다.`;const items=(timelineExpanded?rows:rows.slice(0,6));$("#oracleTimeline").innerHTML=items.map(t=>`<article class="oracle-card"><a class="oracle-thumb" href="${escapeHtml(t.url)}" target="_blank" rel="noreferrer"><img src="${thumbnail(t)}" alt="${escapeHtml(t.title)} 썸네일"/><span>▶ 영상 보기</span></a><div class="oracle-body"><div class="oracle-meta"><span>${t.date.replaceAll("-",".")}</span><span>${t.market}</span></div><h3>${escapeHtml(t.title)}</h3><div class="prediction-compare"><div><small>영상의 전망</small><b class="${t.prediction.toLowerCase()}">${t.prediction==="UP"?"▲ 오를 것":"▼ 내릴 것"}</b></div><span class="compare-arrow">→</span><div><small>실제 시장</small><b class="${t.actual.toLowerCase()}">${t.actual==="UP"?"▲ 올랐음":"▼ 내렸음"} ${fmtPct(t.actualRet)}</b></div></div><div class="oracle-verdict ${t.outcome.toLowerCase()}">${t.outcome==="OPPOSITE"?"↔ 신탁과 반대로 움직임":"✓ 신탁대로 움직임"}</div></div></article>`).join("")||`<div class="empty-story">조건에 맞는 신탁이 없습니다.</div>`;$("#timelineMoreBtn").textContent=timelineExpanded?"접기 ↑":"더 많은 신탁 보기 ↓";$("#timelineMoreBtn").style.display=rows.length>6?"block":"none"}
function renderChart(curve){const svg=$("#equityChart"),w=800,h=300,p=32,all=curve.flatMap(x=>[x.value,x.bench]),min=Math.min(...all,.98),max=Math.max(...all,1.02),x=i=>p+i*(w-2*p)/Math.max(1,curve.length-1),y=v=>h-p-(v-min)*(h-2*p)/(max-min||1),path=key=>curve.map((d,i)=>`${i?"L":"M"}${x(i)},${y(d[key])}`).join(" ");let grid="";for(let i=0;i<5;i++){const yy=p+i*(h-2*p)/4,val=max-i*(max-min)/4;grid+=`<line x1="${p}" y1="${yy}" x2="${w-p}" y2="${yy}" stroke="var(--line)"/><text x="0" y="${yy+3}" fill="var(--muted)" font-size="9" font-family="DM Mono">${((val-1)*100).toFixed(1)}%</text>`}svg.setAttribute("viewBox",`0 0 ${w} ${h}`);svg.innerHTML=`${grid}<path d="${path("bench")}" fill="none" stroke="#90958e" stroke-width="2" stroke-dasharray="4 4"/><path d="${path("value")}" fill="none" stroke="var(--ink)" stroke-width="3"/><path d="${path("value")} L${x(curve.length-1)},${h-p} L${p},${h-p} Z" fill="url(#fade)" opacity=".15"/><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#c8ff32"/><stop offset="1" stop-color="#c8ff32" stop-opacity="0"/></linearGradient></defs>${curve.map((d,i)=>`<circle class="chart-point" data-i="${i}" cx="${x(i)}" cy="${y(d.value)}" r="8" fill="transparent"/>`).join("")}`;$$('.chart-point').forEach(c=>{c.onmouseenter=e=>{const d=curve[+c.dataset.i],tip=$("#tooltip");tip.style.display="block";tip.style.left=`${Math.min(80,(+c.getAttribute("cx")/w)*100)}%`;tip.style.top=`${(+c.getAttribute("cy")/h)*100-5}%`;tip.innerHTML=`${d.date}<br><b>${fmtPct(d.value-1)}</b>`};c.onmouseleave=()=>$("#tooltip").style.display="none"})}
function parseCSV(text){const lines=text.trim().split(/\r?\n/),headers=lines.shift().split(",").map(x=>x.trim());return lines.map((line,i)=>{const vals=[];let cur="",quote=false;for(const ch of line){if(ch==='"')quote=!quote;else if(ch===","&&!quote){vals.push(cur);cur=""}else cur+=ch}vals.push(cur);const o=Object.fromEntries(headers.map((h,j)=>[h,vals[j]?.trim()||""]));return{id:i+1,date:o.date,market:o.market.toUpperCase(),title:o.title,url:o.url||"#",thumbnail:o.thumbnail||"",reason:o.reason||"CSV에서 가져온 신호",prediction:o.prediction.toUpperCase(),open:+o.open,close:+o.close,confidence:+o.confidence||.5,benchmarkReturn:+o.benchmark_return||0}}).filter(x=>x.date&&["NASDAQ","KOSPI"].includes(x.market)&&["UP","DOWN"].includes(x.prediction)&&x.open&&x.close)}
function download(name,content){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$$('#marketControl button').forEach(b=>b.onclick=()=>{$$('#marketControl button').forEach(x=>x.classList.remove('active'));b.classList.add('active');market=b.dataset.value;render()});$$('#strategyControl button').forEach(b=>b.onclick=()=>{$$('#strategyControl button').forEach(x=>x.classList.remove('active'));b.classList.add('active');strategy=b.dataset.value;render()});
$$('#resultControl button').forEach(b=>b.onclick=()=>{$$('#resultControl button').forEach(x=>x.classList.remove('active'));b.classList.add('active');resultFilter=b.dataset.value;render()});$("#timelineMoreBtn").onclick=()=>{timelineExpanded=!timelineExpanded;render()};
$("#costRange").oninput=e=>{cost=+e.target.value/100;$("#costLabel").textContent=`${(+e.target.value).toFixed(2)}%`;render()};$("#searchInput").oninput=e=>{search=e.target.value;render()};$("#showMoreBtn").onclick=()=>{expanded=!expanded;render()};$("#themeBtn").onclick=()=>document.body.classList.toggle("dark");
const dialog=$("#importDialog");$("#importBtn").onclick=()=>dialog.showModal();$("#closeDialog").onclick=()=>dialog.close();$("#chooseFileBtn").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const parsed=parseCSV(reader.result);if(!parsed.length)return alert("유효한 거래 데이터가 없습니다. CSV 열과 값을 확인해 주세요.");trades=parsed;$("#dataStatus").textContent=`가져온 데이터 · ${parsed.length}건`;dialog.close();render()};reader.readAsText(f)};
$("#sampleDownloadBtn").onclick=()=>download("sintak-template.csv","date,market,title,url,thumbnail,prediction,open,close,confidence,benchmark_return\n2025-01-08,NASDAQ,영상 제목,https://youtube.com/watch?v=VIDEO_ID,https://i.ytimg.com/vi/VIDEO_ID/mqdefault.jpg,DOWN,19410,19478,0.82,0.0031");$("#exportBtn").onclick=()=>{const rows=filtered(),head="date,market,title,prediction,actual,outcome,market_return\n",body=rows.map(x=>[x.date,x.market,`\"${x.title.replaceAll('"','""')}\"`,x.prediction,x.actual,x.outcome,x.actualRet].join(",")).join("\n");download("sintak-backtest.csv","\ufeff"+head+body)};
$("#updatedAt").textContent=new Date().toLocaleDateString("ko-KR");render();
