import { mkdir, readFile, writeFile } from 'node:fs/promises';

const API_KEY=process.env.YOUTUBE_API_KEY;
const CHANNEL_ID=process.env.CHANNEL_ID||'UCznImSIaxZR7fdLCICLdgaQ';
const SINCE=new Date('2025-01-01T00:00:00Z');
if(!API_KEY)throw new Error('YOUTUBE_API_KEY 환경 변수가 필요합니다.');

async function google(path,params){const url=new URL(`https://www.googleapis.com/youtube/v3/${path}`);url.search=new URLSearchParams({...params,key:API_KEY}).toString();const response=await fetch(url);if(!response.ok)throw new Error(`YouTube API ${response.status}: ${await response.text()}`);return response.json()}
async function videos(){const channel=await google('channels',{part:'contentDetails',id:CHANNEL_ID});const playlist=channel.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;if(!playlist)throw new Error('업로드 재생목록을 찾지 못했습니다.');const result=[];let pageToken;let finished=false;do{const page=await google('playlistItems',{part:'snippet,contentDetails',playlistId:playlist,maxResults:'50',...(pageToken?{pageToken}:{})});for(const item of page.items||[]){const publishedAt=item.contentDetails?.videoPublishedAt||item.snippet?.publishedAt;if(!publishedAt||new Date(publishedAt)<SINCE){finished=true;break}const id=item.contentDetails?.videoId||item.snippet?.resourceId?.videoId;result.push({id,title:item.snippet.title,description:item.snippet.description||'',publishedAt,thumbnailUrl:item.snippet.thumbnails?.high?.url||item.snippet.thumbnails?.medium?.url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`})}pageToken=page.nextPageToken}while(pageToken&&!finished);return result}

const rules={NASDAQ:/(나스닥|미증시|미국\s?증시|미국\s?주식|빅테크|테슬라|엔비디아|애플|fomc|연준)/i,KOSPI:/(코스피|국장|한국\s?증시|삼성전자|삼전|하이닉스|반도체)/i,DOWN:/(하락|급락|폭락|조정|위기|위험|악재|공포|무너|실패|팔아|현금화|도망)/i,UP:/(상승|급등|반등|오른|오를|돌파|강세|사야|샀|매수|기회|수혜)/i};
function classify(video){const text=`${video.title} ${video.description.slice(0,500)}`;const markets=['NASDAQ','KOSPI'].filter(key=>rules[key].test(text));const directions=['UP','DOWN'].filter(key=>rules[key].test(text));if(markets.length!==1||directions.length!==1)return null;const matched=[...text.matchAll(new RegExp(rules[directions[0]].source,'gi'))].map(x=>x[0]);return{market:markets[0],prediction:directions[0],confidence:Math.min(.92,.68+matched.length*.06),rationale:`제목·설명의 ‘${matched.slice(0,3).join(', ')}’ 표현을 ${directions[0]==='UP'?'상승':'하락'} 전망으로 분류`}}

async function prices(symbol){const start=Math.floor(SINCE.getTime()/1000),end=Math.floor(Date.now()/1000)+86400,url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?period1=${start}&period2=${end}&interval=1d&events=history`;const response=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 SINTAK research'}});if(!response.ok)throw new Error(`시장 데이터 ${symbol}: ${response.status}`);const chart=(await response.json()).chart?.result?.[0];if(!chart)return[];const quote=chart.indicators.quote[0];return chart.timestamp.map((timestamp,i)=>({timestamp:timestamp*1000,date:new Date(timestamp*1000).toISOString().slice(0,10),open:quote.open[i],close:quote.close[i]})).filter(x=>Number.isFinite(x.open)&&Number.isFinite(x.close))}

const [channelVideos,nasdaq,kospi]=await Promise.all([videos(),prices('^IXIC'),prices('^KS11')]);const series={NASDAQ:nasdaq,KOSPI:kospi};let id=1;const events=[];
for(const video of channelVideos){const signal=classify(video);if(!signal)continue;const session=series[signal.market].find(row=>row.timestamp>new Date(video.publishedAt).getTime());if(!session)continue;const marketReturn=session.close/session.open-1,actual=marketReturn>=0?'UP':'DOWN';events.push({id:id++,videoId:video.id,title:video.title,description:video.description,publishedAt:video.publishedAt,thumbnailUrl:video.thumbnailUrl,videoUrl:`https://www.youtube.com/watch?v=${video.id}`,market:signal.market,prediction:signal.prediction,confidence:signal.confidence,rationale:signal.rationale,reviewStatus:'APPROVED',sessionDate:session.date,open:session.open,close:session.close,marketReturn,actual,outcome:actual===signal.prediction?'SAME':'OPPOSITE'})}
events.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt));const output={updatedAt:new Date().toISOString(),source:{channelId:CHANNEL_ID,videoCount:channelVideos.length,oracleCount:events.length,market:'Yahoo Finance daily chart'},events};
await mkdir(new URL('../src/lib/data/',import.meta.url),{recursive:true});await writeFile(new URL('../src/lib/data/oracles.json',import.meta.url),JSON.stringify(output,null,2)+'\n');console.log(`동기화 완료: 영상 ${channelVideos.length}개, 신탁 ${events.length}개`);
